### ISSUE TITLE
Completed Exercises

### ISSUE THREAD

**Issue by ttorkar** [penguinmenac3/robotics-introduction#3]
@penguinmenac3  

Hi Penguin,

Do you have a copy of the completed exercises?

Trent

**Comment by penguinmenac3** [comment]
Yes we have solutions to the tasks, but we are yet unsure how we want to publish them.
We are only sure we do not want to put them in this repository to make cheating a bit more challenging. ;)

**Comment by penguinmenac3** [comment]
We decided to put them in a separate repository: https://github.com/penguinmenac3/robotics-introduction-solutions

In the other repository you will need to "git submodule update --init" in the other repository.
